name: CoreProtect
main: net.coreprotect.CoreProtect
version: ${project.version}
branch: developement
api-version: 1.21
folia-supported: true
website: http://coreprotect.net
author: Intelli
softdepend: [WorldEdit,AdvancedChests]
description: >
             提供服务器的区块保护。
commands:
  co:
    description: 使用 CoreProtect 插件
    permission: coreprotect.co
    permission-message: §3CoreProtect §f- 你没有权限执行此操作。
    usage: /<命令> <参数>
  core:
    description: 使用 CoreProtect 插件
    permission: coreprotect.core
    permission-message: §3CoreProtect §f- 你没有权限执行此操作。
    usage: /<命令> <参数>
  coreprotect:
    description: 使用 CoreProtect 插件
    permission: coreprotect.coreprotect
    permission-message: §3CoreProtect §f- 你没有权限执行此操作。
    usage: /<命令> <参数>
permissions:
    coreprotect.*:
        description: 允许访问所有 CoreProtect 操作和指令
        default: op
        children: 
            coreprotect.rollback: true
            coreprotect.restore: true
            coreprotect.inspect: true
            coreprotect.help: true
            coreprotect.purge: true
            coreprotect.lookup: true
            coreprotect.lookup.near: true
            coreprotect.lookup.chat: true
            coreprotect.lookup.command: true
            coreprotect.lookup.session: true
            coreprotect.lookup.username: true
            coreprotect.lookup.block: true
            coreprotect.lookup.sign: true
            coreprotect.lookup.click: true
            coreprotect.lookup.container: true
            coreprotect.lookup.inventory: true
            coreprotect.lookup.item: true
            coreprotect.lookup.kill: true
            coreprotect.teleport: true
            coreprotect.reload: true
            coreprotect.status: true
            coreprotect.consumer: true
            coreprotect.networking: true
    coreprotect.co:
        description: 允许使用 CoreProtect 的 /co 指令
        default: true
    coreprotect.core:
        description: 允许使用 CoreProtect 的 /core 指令
        default: false
    coreprotect.coreprotect:
        description: 允许使用 CoreProtect 的 /coreprotect 指令
        default: false
    coreprotect.lookup:
        description: 允许使用查询（lookup）指令
        default: op
        children:
            coreprotect.lookup.near: true
            coreprotect.lookup.chat: true
            coreprotect.lookup.command: true
            coreprotect.lookup.session: true
            coreprotect.lookup.username: true
            coreprotect.lookup.block: true
            coreprotect.lookup.sign: true
            coreprotect.lookup.click: true
            coreprotect.lookup.container: true
            coreprotect.lookup.inventory: true
            coreprotect.lookup.item: true
            coreprotect.lookup.kill: true
    coreprotect.lookup.near:
        description: 允许通过 near 指令查询附近的更改
        default: op
    coreprotect.lookup.chat:
        description: 允许查询聊天消息
        default: op
    coreprotect.lookup.command:
        description: 允许查询玩家指令
        default: op
    coreprotect.lookup.session:
        description: 允许查询玩家会话
        default: op
    coreprotect.lookup.username:
        description: 允许查询玩家用户名更改
        default: op
    coreprotect.lookup.block:
        description: 允许查询方块数据
        default: op
    coreprotect.lookup.sign:
        description: 允许查询告示牌内容
        default: op
    coreprotect.lookup.click:
        description: 允许查询玩家交互
        default: op
    coreprotect.lookup.container:
        description: 允许查询容器交易
        default: op
    coreprotect.lookup.inventory:
        description: 允许查询背包交易
        default: op
    coreprotect.lookup.item:
        description: 允许查询物品交易
        default: op
    coreprotect.lookup.kill:
        description: 允许查询实体击杀
        default: op
    coreprotect.rollback:
        description: 允许执行回滚操作
        default: op
    coreprotect.restore:
        description: 允许执行还原操作
        default: op
    coreprotect.inspect:
        description: 允许使用检查器
        default: op
    coreprotect.help:
        description: 允许使用帮助指令
        default: op
    coreprotect.purge:
        description: 允许使用清理（purge）指令
        default: op
    coreprotect.teleport:
        description: 允许使用传送指令
        default: op
    coreprotect.reload:
        description: 允许使用重载指令
        default: op
    coreprotect.status:
        description: 允许使用状态指令
        default: op
    coreprotect.consumer:
        description: 允许使用 consumer 指令
        default: op
    coreprotect.networking:
        description: 允许使用网络 API
        default: op